name: Continuous Deployment

on:
  push:
    tags:
      - '*'

jobs:
  publish-github:
    name: Publish on Github
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build the rootfs
        uses: ./.github/actions/run-arch-command
        inputs:
          run: |
            make
      - name: Upload the release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            rootfs.tar.gz
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
