name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_fakeroot-tcp:
    name: Build fakeroot-tcp
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build the package
        uses: ./.github/actions/run-arch-command
        with:
          run: |
            curl -O https://aur.archlinux.org/cgit/aur.git/snapshot/fakeroot-tcp.tar.gz
            tar xvf fakeroot-tcp.tar.gz
            sudo chown -R makepkg fakeroot-tcp
            cd fakeroot-tcp
            yes | sudo -u makepkg makepkg -src
            cp *.pkg.tar.zst ..
            cd ..
      - name: Store packages as artifacts for RootFS compilation
        uses: actions/upload-artifact@v4
        with:
          name: fakeroot-tcp
          path: |
            ${{ github.workspace }}/*.pkg.tar.zst

  build_glibc-linux4:
    name: Build glibc-linux4
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build the package
        uses: ./.github/actions/run-arch-command
        with:
          run: |
            curl -O https://aur.archlinux.org/cgit/aur.git/snapshot/glibc-linux4.tar.gz
            tar xvf glibc-linux4.tar.gz
            sudo chown -R makepkg glibc-linux4
            cd glibc-linux4
            yes | sudo -u makepkg env MAKEFLAGS="-j$(nproc)" makepkg -src
            cp *.pkg.tar.zst ..
            cd ..
      - name: Store packages as artifacts for RootFS compilation
        uses: actions/upload-artifact@v4
        with:
          name: glibc-linux4
          path: |
            ${{ github.workspace }}/*.pkg.tar.zst

  compile:
    name: Compile RootFS
    runs-on: ubuntu-latest
    needs: [build_fakeroot-tcp, build_glibc-linux4]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          merge-multiple: true
      - name: Show the current status
        run: ls -R
      - name: Keep only relevant packages
        run:
          rm -v *debug*.pkg.tar.zst lib32-*.pkg.tar.zst
          mv -v fakeroot-tcp-*.pkg.tar.zst fakeroot-tcp.pkg.tar.zst
          mv -v glibc-linux4-*.pkg.tar.zst glibc-linux4.pkg.tar.zst
      # Standard stuff
      - name: Build the rootfs
        run: make
