name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  compile:
    name: Compile rootfs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Who am I?
        run: |
          whoami
          id
      - name: Prepare build folder for Arch packages
        uses: ./.github/actions/run-arch-command
        with:
          run: |
            sudo mkdir -p .build
            sudo chown build .build
      - name: Build the package 'glibc-linux4'
        uses: ./.github/actions/run-arch-command
        with:
          run: make glibc-linux4.pkg.tar.zst
      - name: Build the package 'fakeroot-tcp'
        uses: ./.github/actions/run-arch-command
        with:
          run: make fakeroot-tcp.pkg.tar.zst
      - name: Copy the packages to the proper spot
        run: |
          cp -v .build/fakeroot-tcp/fakeroot-tcp-*.pkg.tar.zst .
          cp -v .build/glibc-linux4/glibc-linux4-*.pkg.tar.zst .
      - name: Build the rootfs
        run: make
