name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  compile:
    name: Compile rootfs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build the package 'glibc-linux4'
        uses: ./.github/actions/run-arch-command
        with:
          run: make fakeroot-tcp.pkg.tar.zst
      - name: Build the package 'fakeroot-tcp'
        uses: ./.github/actions/run-arch-command
        with:
          run: make fakeroot-tcp.pkg.tar.zst
      - name: Build the rootfs
        run: make
