name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  compile:
    name: Compile rootfs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # fakeroot-tcp
      - name: Cache fakeroot-tcp
        id: cache-fakeroot-tcp
        uses: actions/cache@v4
        with:
          path: fakeroot-tcp.pkg.tar.zst
          key: cache-fakeroot-tcp
      - name: Build the package 'fakeroot-tcp'
        if: steps.cache-fakeroot-tcp.outputs.cache-hit != 'true'
        uses: ./.github/actions/run-arch-command
        with:
          run: |
            sudo -u build make fakeroot-tcp.pkg.tar.zst
      - name: Copy the 'fakeroot-tcp' package to the proper spot
        if: steps.cache-fakeroot-tcp.outputs.cache-hit != 'true'
        run: |
          cp -v /github/workspace/.build/fakeroot-tcp/fakeroot-tcp-*.pkg.tar.zst fakeroot-tcp.pkg.tar.zst

      # glibc-linux4
      - name: Cache glibc-linux4
        id: cache-glibc-linux4
        uses: actions/cache@v4
        with:
          path: glibc-linux4.pkg.tar.zst
          key: cache-glibc-linux4
      - name: Build the package 'glibc-linux4'
        if: steps.cache-glibc-linux4.outputs.cache-hit != 'true'
        uses: ./.github/actions/run-arch-command
        with:
          run: |
            export MAKEFLAGS=-j$(nproc)
            sudo -u build make glibc-linux4.pkg.tar.zst
      - name: Copy the 'fakeroot-tcp' package to the proper spot
        if: steps.cache-glibc-linux4.outputs.cache-hit != 'true'
        run: |
          cp -v /github/workspace/.build/glibc-linux4/glibc-linux4-*.pkg.tar.zst glibc-linux4.pkg.tar.zst


      # Standard stuff
      - name: Build the rootfs
        run: make
